### ISSUE TITLE
add gitpod.yml

### ISSUE THREAD

**Issue by uchicom** [uchicom/csve#4]
```
tasks:
  - name: download library
    init: mvn spotless:apply verify
github:
  prebuilds:
    pullRequests: false
    addComment: false
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-pack
    - donjayamanne.githistory
    - github.vscode-pull-request-github
```
